auth_request_set $refreshed_session_cookie $upstream_http_set_cookie;
auth_request_set $refreshed_session_cookie_1 $upstream_http_x_authz_set_cookie_1;
auth_request_set $refreshed_session_cookie_2 $upstream_http_x_authz_set_cookie_2;
auth_request_set $refreshed_session_cookie_3 $upstream_http_x_authz_set_cookie_3;
add_header Set-Cookie $refreshed_session_cookie always;
add_header Set-Cookie $refreshed_session_cookie_1 always;
add_header Set-Cookie $refreshed_session_cookie_2 always;
add_header Set-Cookie $refreshed_session_cookie_3 always;
